### ISSUE TITLE
Titel / oberen Rand vergrößert darstellen

### ISSUE THREAD

**Issue by jnorulez** [crazzle/SwitchR#2]
Für die Usability wäre es aus meiner Sicht hilfreich, entweder den oberen Rand eines Fensters vergrößert darzustellen oder den Titel mit einzublenden. 

Beispiel: Wenn ich zB IntelliJ 4x aufhabe, kann ich anhand des Repo Namens oben am besten erkennen, was was ist aber der ist so klein.

**Comment by crazzle** [comment]
Fixed.
